apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configmapmaps.operators.dstream.cloud
spec:
  group: operators.dstream.cloud
  names:
    kind: ConfigMapMap
    listKind: ConfigMapMapList
    plural: configmapmaps
    singular: configmapmap
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ConfigMapMap is the Schema for the configmapmaps API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ConfigMapMapSpec defines the desired state of ConfigMapMap
          properties:
            data:
              additionalProperties:
                description: ConfigMapMapSpecItem defines item to be merged
                properties:
                  kind:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                  subPath:
                    type: string
                type: object
              type: object
            name:
              type: string
            namespace:
              type: string
          type: object
        status:
          description: ConfigMapMapStatus defines the observed state of ConfigMapMap
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
